# The rules below are inspired by those found here:
# https://github.com/ebnn/draftcheck/blob/master/draftcheck/rules.py
rule("centering",r"\\begin{center}", "Use \\centering instead of \\begin{center}")
rule("footnote_spaces",r"\s+\\footnote{", "Do not precede footnotes with spaces.")
rule("citations_before_period",r"\.\\cite{", "Place citations before periods with a non-breaking space."),
rule("url", r"(?<!\\url{)(\bhttps?://)[^\s.]+\.[-A-Za-z0-9+&@#/%?=~_|!:,.;]+", "Wrap URLs with the \\url command.")
rule("left_and_right_quotes",r"\s\'.+?\'[\s\.,]", "Use left and right quotation marks ` and ' rather than '")
rule("citation_nouns",r"\b(:?in|as|on|by)[ ~]\\cite{", "Avoid using citations as nouns.")
rule("non-breaking_space_citation", r"[^~]\\ref{", "Place a single, non-breaking space '~' before references.")
rule("escape_percent",r"\d+%", "Escape percentages with backslash.")
rule("punctuation", r"\s[,;.!?]", "Do not precede punctuation characters with spaces.")
rule("mutiply",r"\d+\s?x\d+", "When multiplying, do not use 'x' and instead use \$\\times\$.")
rule("duplicate",r"\b([a-z]+)\s+\1\b(?![^{]*})", "Remove duplicated word.")
rule("ellipses",r"\.\.\.", "Typeset ellipses by \\dots, not ...")
rule("non-breaking_space_periods",r"\.\\cite{", "Place citations before periods with a non-breaking space.")
rule("double_quotes",r"\"", "Use left and right quotation marks `` and '' rather than \".")
rule("begin_equation",r"^\$\$", "Use \[ or \\begin{equation} instead of \$\$")
rule("endash", r"\d\s?-\s?\d", "Use endash '--' for numeric ranges instead of hyphens.")
rule("footnotes_after_punc", r"\\footnote{.+?}[,;.?]", "Place footnotes after punctuation marks.")
rule("angle_brac",r"<[^\s](.+?)[^\s]>", "Use \\langle and \\rangle instead of '<' and '>' for angle brackets.")
rule("use_cite", r"\\cite{.+?}\s?\\cite{", "Use \\cite{...,...} for multiple citations")
rule("space_num_unit",r"\d(m|A|kg|s|K|mol|cd)\b", "Place a non-breaking space between a number and its unit.")
rule("backslash_space",r"\b(e\.g\.|i\.e\.)\s+", "Place a '\\ ' (backslash space) after the period of an abbreviation.")
rule("def_command",r"\\def\\[a-z]+{", "Do not use the \\def command. Use \\newcommand instead.")
rule("sloppy",r"\\sloppy", "Avoid the \\sloppy command.")
rule("space_quotes",r"'''|```", "Use a thin space \, to separate quotes.")
rule("ordinal_numbers",r"1st|2nd|3rd", "Spell out ordinal numbers (1st, 2nd, etc.) in words.")
rule("single_digit_spell",r"[a-z]+ \d [a-z]+", "Spell out single digit numbers in words.")
rule("single_space_period",r"\.  [A-Z]", "Prefer single space over double space after a period.")
